# Generated by Django 3.1.1 on 2020-10-01 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(default='e2b055be-1c39-409a-9ea1-f9317442684a', on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='shop.order'),
            preserve_default=False,
        ),
    ]
