# Generated by Django 3.1.1 on 2020-10-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
